### ISSUE TITLE
Is it possible to reserve the time of <pubDate> of each item ?

### ISSUE THREAD

**Issue by AboutRSS** [damoeb/rss-proxy#10]
Thanks for this great tool. Just wondering if it is possible that the pubDate of each item in the generated RSS feed won't be modified according to the time when this RSS feed is freshened / generated. I mean the pubDate of each item in the feed is essential for me. The time in `pubDate` is better to stay unchanged. I know this is also a problem for other PAGE2RSS tools like Feed43.com. Wish there is a way to solve this issue.

**Comment by damoeb** [comment]
Hi, thanks for bringing it up. The solution is very related to the solution for full-feed (https://github.com/damoeb/rss-proxy/issues/9).  It is just a bit more complicated, but I am working on it.

**Comment by damoeb** [comment]
I decided to publish a solution in a different project called rich-RSS (https://github.com/damoeb/rich-rss), cause it does not work with the current stateless approach of rss-proxy. To resolve the pubDate in a reasonable way, polling is required. Polling can only work with the knowledge of what feeds/sites should be watched. This knowledge can be seen as a subscription to a feed, which is the core idea of rich-RSS. There you will be able to get fulltext feeds, correct metadata among others.

I will close the issue.
