### ISSUE TITLE
help with feed?

### ISSUE THREAD

**Issue by somedevreally** [damoeb/rss-proxy#11]
Hello,

am trying to get feed for firmware updates on asus site, but i cant get the feed properly, need help
`https://www.asus.com/Networking-IoT-Servers/WiFi-Routers/ASUS-WiFi-Routers/RT-AC5300/HelpDesk_BIOS/`

is it possible? 

thanks

**Comment by damoeb** [comment]
The problem is that the site rendered using JavaScript. I have a feature in progress to support that kind of websites using puppeteer, its almost done.

**Comment by damoeb** [comment]
`rss-proxy` now supports your use case. More details on this [issue](https://github.com/damoeb/rss-proxy/issues/4)
