### ISSUE TITLE
JSON2RSS

### ISSUE THREAD

**Issue by amblerkr** [damoeb/rss-proxy#17]
I knew you were solving my problem. Thank you.
I can't pay a lot of money, but I'm willing to pay.
It should be easy and available even if it is not a developer. With a little knowledge. No-code!!!

---
Korean Many sites do not provide RSS feeds. I figured out how to find JSON.
It would be very convenient if you could convert it to RSS feed. If this is resolved, you will be able to create rss from a service that does not provide other RSS.

Your service cannot designate a title or set a link directly. I want this kind of service.
https://github.com/RSS-Bridge/rss-bridge/blob/master/bridges/XPathBridge.php

---
# V LIVE

## Website URL
// SMTOWN
https://www.vlive.tv/channel/FD53B/board/3530
https://www.vlive.tv/channel/FD53B/board/69
// aespa
https://www.vlive.tv/channel/97CCED/board/7553
https://www.vlive.tv/channel/97CCED/board/7375
// V MUSICAL
https://www.vlive.tv/channel/EDE229/board/4029

## Website description
V LIVE : LIVE STREAM, FAN COMMUNNITY
SM Entertainment has closed the artist's official site. From now on, they will post announcements through V LIVE.

## What content should be included?
New video, New Post

## Additional description
I looked for something that might help.
https://github.com/gdegauquier/vlive-api
https://github.com/robindz/VSharp
https://github.com/Seklfreak/Robyul2/blob/master/modules/plugins/vlive.go

---
# JSON2RSS
https://json2feed.ssig33.com/
https://github.com/ssig33/json2feed

https://crssnt.com/

e.g)
NAVER POST
https://post.naver.com/my.nhn?memberNo=41350603

JSON (async/ajax/api):
https://m.post.naver.com/async/my.nhn?memberNo=41350603&postListViewType=0&isExpertMy=true

**Comment by damoeb** [comment]
```
<feed xmlns="http://www.w3.org/2005/Atom">
<id>https://www.vlive.tv/channel/FD53B/board/3530</id>
<title>V LIVE via rss-proxy</title>
<updated>2021-01-09T14:26:32.115Z</updated>
<generator>rss-proxy 1.0.2</generator>
<link rel="alternate" href="https://www.vlive.tv/channel/FD53B/board/3530"/>
<entry>
<title type="html"><![CDATA[U-KNOW - NOIR Film EP.1 'Need You Right Now'play100Klike2.1Mcommentboardlist / ic_comment2K]]></title>
<id>tag:rss-proxy.migor.org:https://www.vlive.tv/post/0-20762334</id>
<link href="https://www.vlive.tv/post/0-20762334"/>
<updated>2021-01-09T14:26:32.115Z</updated>
<published>2021-01-09T14:26:32.115Z</published>
</entry>
<entry>
<title type="html"><![CDATA[aespa "Black Mamba" MV Behind The Scenesplay42Klike617Kcommentboardlist / ic_comment28aespa(에스파) channel's video.]]></title>
<id>tag:rss-proxy.migor.org:https://www.vlive.tv/post/1-20766468</id>
<link href="https://www.vlive.tv/post/1-20766468"/>
<updated>2021-01-09T14:26:32.115Z</updated>
<published>2021-01-09T14:26:32.115Z</published>
</entry>
...

The recent patch 1.0.2 fixes the issue with the links. if you run `docker pull damoeb/rss-proxy:js` and then run that image (see readme) you should see an ok feed. You may play around with the *Feed Entry Content* flag.

Can you run it yourself or would you want me to host it? If you cannot run it yourself, I could host it within the next 2 weeks or so. Cheers!

**Comment by damoeb** [comment]
@amblerkr Did you have time to check if the latest version fixes you issues? I will close the issue for now, cause I consider it to be fixed.

**Comment by amblerkr** [comment]
How can I use it? It would be very thankful if you explain it easily.
