### ISSUE TITLE
Feature request: preview of feeds

### ISSUE THREAD

**Issue by Maetran** [damoeb/rss-proxy#18]
Can you implement a preview of the generated feeds?
My usecase:

- feed is getting explored
- choose your feed (depending on score)
- while staying mouseover the chosen feed show a preview of the generated feed (in a popup?) to see if the correct querrys have been selected and how it will / could be displayed in the rss aggregator
Would be awesome!

**Comment by damoeb** [comment]
I am not sure if a xml feed in a popup is usefull, though I imagine that a feed in a separate tab next to the visualized website could serve a useful. As a work around you could just click on the "Your ATOM Feed" link and check the actual feed. Using browser extensions you will get highlighting as well, which I recommend anyway for viewing XMLs.

I will add it to the long list, for now, I will tag it with "wont fix"/
