### ISSUE TITLE
Feed loads in browser – but Feedly cannot find it

### ISSUE THREAD

**Issue by georgjaehnig** [damoeb/rss-proxy#29]
Hi, I've tested this on the mirror at https://rssproxy.blyat.org/

It seems that every feed I generate
- is properly displayed when called in the browser
- but when trying to import in Feedly, they say: "We were not able to find an RSS feed for https://…"

Example:
- https://rssproxy.blyat.org/?url=https:%2F%2Fwww.heise.de%2F
- and then using the first feed with the highest score

**Comment by georgjaehnig** [comment]
Nevermind, now Feedly accepts it. Probably only a hickup at theirs.

**Comment by damoeb** [comment]
Cool :)
