### ISSUE TITLE
Is it possible to support multiply feeds?

### ISSUE THREAD

**Issue by cmsxbc** [damoeb/rss-proxy#34]
As the title says, when multiply feeds are extracted, and they are all valid. It's better if we can select multiply feeds.

**Comment by damoeb** [comment]
Hi, this is not possible, but I am working on a followup tool called [rich-rss](https://github.com/damoeb/rich-rss) where you can do all of that, aggregating, filtering, tagging, fulltext-extraction. My timeline is that in about 2 month I will have a first stable version.
