### ISSUE TITLE
Blank screen on demo page

### ISSUE THREAD

**Issue by raokrutarth** [damoeb/rss-proxy#35]
Hi! I'm building https://newssnips.fyi/about and wanted to use this service for websites that don't have an rss feed. Would you be interested in helping out on the project by restarting the demo site? 

Or, to provide an updated copy of a working version?

**Comment by damoeb** [comment]
Maybe, I did a rewrite of rss-proxy in kotlin, which performs much better, rss-proxy is quite slow and unstable. The rewrite is part of the followup project rich-rss, but its still work in progress and it will take another 2 month for the first release. I will keep you posted.
