### ISSUE TITLE
Prioritize semantic HTML.

### ISSUE THREAD

**Issue by SuperSonicHub1** [damoeb/rss-proxy#36]
I was trying your site on [Audacity's blog](https://www.audacityteam.org/posts/) since it tragically lacks an RSS feed and noticed some issues with your algorithm for detecting articles, and I believe this is because you don't prioritize semantic HTML enough.

To understand what semantic HTML is, see MDN's [HTML: A good basis for accessibility](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML).

Audacity luckily does have their articles in `<article>` tags, which makes them extremely accessible for us, yet it's the **fourth** best option. (Also, the fourth option contains 10 articles, not 3.)

![The actual best feed](https://user-images.githubusercontent.com/25624882/146683282-f99c563a-d481-4874-a9b3-3ac123c13e39.png)

The best one according to your algorithm selects some paragraphs in the middle of an article.

![The best but actually really bad feed](https://user-images.githubusercontent.com/25624882/146683323-3f968620-c0a9-4030-b0c9-351f830ace05.png)

You would also do best to rank feeds in `<aside>` and `<footer>` elements poorly or simply not show them to the user at all, as these clutter the bottom of the list.

Hope this is helpful!

**Comment by damoeb** [comment]
Thanks for the input, I will consider this in my current rewrite.

**Comment by SuperSonicHub1** [comment]
Seems to work a lot better! Thanks for keeping my suggestions in mind.
