### ISSUE TITLE
Can not install on Docker

### ISSUE THREAD

**Issue by qupb** [damoeb/rss-proxy#45]
Is that image name right?
I found damoeb/rss-proxy:2.0.0-beta but no damoeb/rss-proxy:2

**Comment by damoeb** [comment]
Yes, its still beta i merged a bit prematurely. If you want to run the beta, let me know, than I share the docker-compose and nginx reverse proxy settings I currently use.

**Comment by damoeb** [comment]
I fixed the documentation. Check https://github.com/damoeb/rss-proxy/#quickstart-version-2-using-docker-compose-experimental

**Comment by qupb** [comment]
Still can not work properly
my mirror website: https://rss.319712.xyz/
