### ISSUE TITLE
error when running version 2

### ISSUE THREAD

**Issue by simpread** [damoeb/rss-proxy#57]
ERROR FeedEndpoint - [Sz2K] Unable to discover feeds: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @52af6cff
![图片](https://user-images.githubusercontent.com/81662464/206643700-9767167d-cb0b-470d-98d0-c09e487616d3.png)

**Comment by karousn** [comment]
same here. any correction or workaround?
