### ISSUE TITLE
What does 'undefined' mean, when fetching feeds?

### ISSUE THREAD

**Issue by 07416** [damoeb/rss-proxy#61]
I'm getting the error when attempting to 'show feeds' for some sources. I've confirmed that the webpages don't require Javascript. This doesn't affect all pages.

The error message appears on the right-hand panel.

---

rss-proxy v. 1.0.3 @0b5334a build on 16-0-2021

some affected websites or pages:

`https://www.eurogamer.net/`
`https://yle.fi/uutiset/18-194469`

**Comment by damoeb** [comment]
Hi, sry for the late response, I updated the backend with a version that runs much better, you wan't to retry?

**Comment by 07416** [comment]
> Hi, sry for the late response, I updated the backend with a version that runs much better, you wan't to retry?

I see no immediate issues with v2.1.0 @909fdd2
