### ISSUE TITLE
https://rssproxy.migor.org/ Leads to 502 Bad Gateway

### ISSUE THREAD

**Issue by pottsy292** [damoeb/rss-proxy#71]
Seems the server is currently down.
Has been for a couple of days

the webpage https://rssproxy.migor.org/ is leading to…

502 Bad Gateway

nginx/1.18.0 (Ubuntu)

**Comment by Akagi201** [comment]
Use https://github.com/wezm/rsspls for simple static site and rsshub for complicated site.

**Comment by Amr0077** [comment]
> Use https://github.com/wezm/rsspls for simple static site and rsshub for complicated site.

hi, Can you teach me how to make  rss feed in rsshub? I installed it on my device, but it is very complicated and there is no explanation on the Internet about how it works

I know I'm torturing you with me, but even https://rsspls.7bit.org/ I didn't know how it worked

**Comment by pottsy292** [comment]
Cheers, I’ll have a look when I’m home.
I currently use the https://rssproxy.migor.org/ for a few rss feeds but they have gone down and I’m away on holiday.

Hopefully be able to get through the documentation and get them running again with your suggestion once I’m home. I get the feeling this maybe down for good.

Cheers pal.

**Comment by damoeb** [comment]
I will take a look

**Comment by damoeb** [comment]
Its up again

**Comment by damoeb** [comment]
its up again, this version does not restart yet once it dies.
